In [1]:
import pandas as pd

In [2]:
X = pd.read_csv('../data/processed/X.csv')
y = pd.read_csv('../data/processed/y.csv')

In [3]:
X.head()

,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,Bowler,Batter Runs,...,Batter Balls Faced,Non Striker Balls Faced,Bowler Runs Conceded,Valid Ball,is_six,bowler_wickets,is_dot_ball,Year,bat_first_win_rate,bat_second_win_rate
0,9,0,6,1,1,1,442,159,458,4,...,1,0,4,1,0,1,0,2023,0.588785,0.504505
1,9,0,6,1,1,2,442,159,458,0,...,2,0,0,1,0,1,1,2023,0.588785,0.504505
2,9,0,6,1,1,3,442,159,458,0,...,3,0,0,1,0,1,1,2023,0.588785,0.504505
3,9,0,6,1,1,4,442,159,458,0,...,4,0,0,1,0,1,1,2023,0.588785,0.504505
4,9,0,6,1,1,5,442,159,458,1,...,5,0,1,1,0,1,0,2023,0.588785,0.504505

In [4]:
y.head()

                Winner
0  Chennai Super Kings
1  Chennai Super Kings
2  Chennai Super Kings
3  Chennai Super Kings
4  Chennai Super Kings